"""empty message

Revision ID: 0fd49f5418b3
Revises: dd15cb02f7fe
Create Date: 2019-05-18 16:22:19.101830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fd49f5418b3'
down_revision = 'dd15cb02f7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('电阻')
    op.drop_table('二极管')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('二极管',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='二极管_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('电阻',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('硬度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('强度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('浓度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('魔抗', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('血量', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('属性1', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='电阻_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
