"""empty message

Revision ID: 68c5ef8550b7
Revises: b1389ea3371e
Create Date: 2019-04-29 10:59:53.201471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68c5ef8550b7'
down_revision = 'b1389ea3371e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', '发生数量')
    op.drop_column('material_detail', '小薰')
    op.drop_column('material_detail', '擦擦擦')
    op.drop_column('material_detail', '魔王')
    op.drop_column('material_detail', '电容')
    op.drop_column('material_detail', '阻值')
    op.add_column('materials', sa.Column('物料库存', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', '物料库存')
    op.add_column('material_detail', sa.Column('阻值', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('material_detail', sa.Column('电容', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('material_detail', sa.Column('魔王', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('material_detail', sa.Column('擦擦擦', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('material_detail', sa.Column('小薰', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('inventory', sa.Column('发生数量', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
