"""empty message

Revision ID: 8d94225a21f3
Revises: a8995534d095
Create Date: 2019-05-06 10:40:44.145961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d94225a21f3'
down_revision = 'a8995534d095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('二极管')
    op.drop_table('蝙蝠侠')
    op.drop_table('电阻')
    op.drop_table('蜘蛛侠')
    op.drop_table('炒面')
    op.drop_table('浩克')
    op.drop_table('电容')
    op.drop_table('吸血鬼')
    op.drop_table('电路板')
    op.drop_table('皮卡丘')
    op.drop_table('超人')
    op.drop_table('狼人')
    op.drop_column('material_detail', 'aa')
    op.add_column('materials', sa.Column('备注', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', '备注')
    op.add_column('material_detail', sa.Column('aa', mysql.VARCHAR(length=10), nullable=True))
    op.create_table('狼人',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('超人',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('皮卡丘',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('电路板',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='电路板_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('吸血鬼',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('电容',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='电容_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('浩克',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('炒面',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('蜘蛛侠',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('电阻',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jack', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('bbb', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fight', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='电阻_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('蝙蝠侠',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('二极管',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('啧啧啧', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='二极管_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
