"""empty message

Revision ID: 9494b2033d55
Revises: a4900816fb38
Create Date: 2019-04-26 11:31:55.935682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9494b2033d55'
down_revision = 'a4900816fb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_detail',
    sa.Column('编号', sa.Integer(), nullable=False),
    sa.Column('物料ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], ),
    sa.PrimaryKeyConstraint('编号')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_detail')
    # ### end Alembic commands ###
