"""empty message

Revision ID: a4900816fb38
Revises: acbabb3c521d
Create Date: 2019-04-24 13:06:56.749659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4900816fb38'
down_revision = 'acbabb3c521d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials_product_info',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('封装名称', sa.String(length=64), nullable=False),
    sa.Column('封装数量', sa.String(length=64), nullable=True),
    sa.Column('倍率', sa.String(length=64), nullable=True),
    sa.Column('生产数量', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials_product_info')
    # ### end Alembic commands ###
