"""empty message

Revision ID: b872fd9bb6a6
Revises: 7487c48ffa2c
Create Date: 2019-04-16 13:41:39.482189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b872fd9bb6a6'
down_revision = '7487c48ffa2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_flow',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('价格', sa.Float(), nullable=False),
    sa.Column('日期', sa.DateTime(), nullable=True),
    sa.Column('类型', sa.Boolean(), nullable=True),
    sa.Column('发生数量', sa.Integer(), nullable=False),
    sa.Column('库存数量', sa.Integer(), nullable=False),
    sa.Column('物料名称', sa.String(length=64), nullable=True),
    sa.Column('物料ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_flow')
    # ### end Alembic commands ###
