"""empty message

Revision ID: dd15cb02f7fe
Revises: 61622d95a502
Create Date: 2019-05-15 15:03:29.761826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd15cb02f7fe'
down_revision = '61622d95a502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('二极管')
    op.drop_table('程序')
    op.drop_table('测试5')
    op.drop_table('测试2')
    op.drop_table('测试')
    op.drop_table('电阻')
    op.drop_table('以太网')
    op.drop_table('棒球')
    op.drop_table('测试4')
    op.drop_table('测试3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('测试3',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='测试3_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('测试4',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='测试4_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('棒球',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='棒球_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('以太网',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='以太网_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('电阻',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('浓度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('灰度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('熔点', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('融点', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('硬度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('密度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('bb', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('ggg', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('lll', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('长度', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('点灯', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('爆炸', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('None', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('蒜头王八', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('pika', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('钉钉', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='电阻_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('测试',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='测试_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('测试2',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='测试2_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('测试5',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='测试5_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('程序',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='程序_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('二极管',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('物料ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('棒棒糖', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('魔法值', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['物料ID'], ['materials.ID'], name='二极管_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
